---
title: "Data Collection File"
output: html_notebook
---

Need to run devtools::install_github("vdeminstitute/vdemdata")

```{r set_up}
library(tidyverse)
library(janitor)
library(vdemdata)
library(readxl)
library(rdrop2)
library(states)

# Read in Dropbox token

token <- readRDS("token.rds")

# Then pass the token to the drop_acc function

drop_acc(dtoken = token)

# Read in ISO country codes for merging with data sets missing them

country_code <- read_excel("ViEWS/country_code.xls", skip = 2) %>%
  clean_names() %>%
  rename(country_code = iso_alpha_3_code,
         country_name = country_or_area_name)
```


## World Bank Indicators
https://databank.worldbank.org/source/world-development-indicators#

```{r world_bank}
####################################################################
# POPULATION DATA

population <- read_csv("ViEWS/population.csv") %>%
  clean_names()

# Fix naming, remove excess from year values

colnames(population) <- c("country_name", "country_code", 
                                          "series_name", "series_code", 
                          substring(colnames(population[5:ncol(population)]), 
                                    2, 5))

# Remove excess columns, create year data column, run log() on data

population_fixed <- population %>%
  select(-c(series_name, series_code, "2020")) %>%
  pivot_longer(cols = -c(country_name, country_code), 
               names_to = "year", values_to = "pop") %>%
  mutate(pop = as.numeric(pop),
         pop_ln = log(pop))


####################################################################
# GDP PER CAPITA, 2017 PPP

# Read in data

gdp_2017 <- read_csv("ViEWS/gdp_capita_2017ppp.csv") %>%
  clean_names()

# Fix naming of year columns

colnames(gdp_2017) <- c("country_name", "country_code", 
                                          "series_name", "series_code", 
                        substring(colnames(gdp_2017[5:ncol(gdp_2017)]), 2, 5))

# Fix by creating a column for year, removing excess columns, take log 

gdp_2017_fixed <- gdp_2017 %>%
  select(-c(series_name, series_code, "2020")) %>%
  pivot_longer(cols = -c(country_name, country_code), 
               names_to = "year", values_to = "gdp_cap") %>%
  mutate(gdp_cap = as.numeric(gdp_cap),
         gdp_cap_ln = log(gdp_cap))


####################################################################
# OIL RENTS

# Read in data

oil_rents <- read_csv("ViEWS/oil_rents_perc.csv") %>%
  clean_names()

# Fix naming of year columns

colnames(oil_rents) <- c("country_name", "country_code", "series_name", 
                         "series_code", 
                         substring(colnames(oil_rents[5:ncol(oil_rents)]), 2, 5))

# Create a column for year, convert percentage to decimal value

oil_rents_fixed <- oil_rents %>%
  select(-c(series_name, series_code, "2020")) %>%
  pivot_longer(cols = -c(country_name, country_code), 
               names_to = "year", values_to = "rent_perc") %>%
  mutate(rent_perc = as.numeric(rent_perc) / 100)
```

## V-DEM Democracy Index

Autocracy and Democracy Categorization
https://www.v-dem.net/files/5/Regimes%20of%20the%20World%20-%20Final.pdf

```{r vdem}
# Read in data from VDEM library, select columns identified by VDEM as being 
# relevant to identifying regime type

dem_data <- vdem %>%
  select(country_name, country_text_id, year, v2x_polyarchy, 
         v2x_partip, v2x_liberal) %>%
  group_by(country_name, country_text_id, year) %>%
  summarize(dem_index = mean(c(v2x_polyarchy + v2x_partip + v2x_liberal), na.rm = TRUE)) %>%
  rename(country_code = country_text_id)

# Define as autocracy or type of democracy

regime_type <- vdem %>%
  select(country_name, country_text_id, year, 
         v2elmulpar_osp, v2elfrfair_osp, v2x_polyarchy,
         v2clacjstm_osp, v2clacjstw_osp, v2x_liberal) %>%
  mutate(regime_type = case_when(
    v2elmulpar_osp < 2 ~ "autocracy",
    v2elfrfair_osp < 2 ~ "autocracy",
    v2x_polyarchy < 0.5 ~ "autocracy",
    v2x_polyarchy < 0.5 ~ "autocracy",
    v2clacjstm_osp < 3 ~ "semi-democracy",
    v2clacjstw_osp < 3 ~ "semi-democracy",
    v2x_liberal < 0.8 ~ "semi-democracy",
    TRUE ~ "democracy")) %>%
  select(country_name, country_text_id, year, regime_type) %>%
  rename(country_code = country_text_id) %>%
  mutate(value = 1) %>%
  pivot_wider(names_from = "regime_type", values_from = "value")

regime_type[is.na(regime_type)] <- 0
```

## First Data Merge (for testing)

```{r merge_a}

country_predictors <- gdp_2017_fixed %>%
  merge(oil_rents_fixed, all = TRUE, 
        by = c("country_name", "year", "country_code")) %>%
  merge(population_fixed, all = TRUE, 
        by = c("country_name", "year", "country_code")) %>%
  mutate(rent_cap = gdp_cap * rent_perc,
         cap_no_rent = gdp_cap - rent_cap) %>%
  merge(dem_data[,2:4], all = TRUE, 
        by = c("year", "country_code")) %>%
  merge(regime_type[,2:6], all = TRUE, 
        by = c("year", "country_code"))

country_predictors <- country_predictors %>%
  arrange(country_code, year) %>%
  drop_na(country_name)
```

# Conflict Data

## ACLED CONFLICT DATA
https://acleddata.com/data-export-tool/

```{r acled}
# This is the code used to create acled_modified from the original datafile:

# acled_data <- read_csv("ViEWS/acled_data.csv") %>%
#   clean_names() %>%
#   select(year, event_type, country, iso3)
#   
# acled_fixed <- acled_data %>%
#   filter(!event_type == "Strategic developments") %>%
#   mutate(event_type = case_when(
#     (event_type %in% c("Protests", "Riots")) ~ 14,
#     (event_type == "Violence against civilians") ~ 18,
#     (event_type %in% c("Battles", "Explosions/Remote violence")) ~ 19)) %>%
#   group_by(year, iso3, event_type) %>%
#   summarize(total = n()) %>%
#   rename(country_code = iso3)

# write_csv(acled_fixed, path = "ViEWS/acled_modified.csv")

# Read in ACLED

acled_fixed <- read_csv("ViEWS/acled_modified.csv") %>%
  rename(acled_total = total)

# Merge ACLED with full_data

conflict_data <- acled_fixed
```

## CORRELATES OF WAR

```{r correlates}
# https://correlatesofwar.org/data-sets
```

## UCDP ORGANIZED EVENTS
https://ucdp.uu.se/downloads/

```{r ucdp}
# Create data from original data file

organized <- read_csv("ViEWS/full_data/ged201.csv") %>%
  select(year, type_of_violence, country_id) %>%
  rename(cowcode = country_id) %>%
  merge(cowstates, by = "cowcode", all.x = TRUE) %>%
  select(type_of_violence, cow3c, year) %>%
  rename(country_code = cow3c) %>%
  group_by(country_code, year, type_of_violence) %>%
  mutate(type_of_violence = type_of_violence,
         type_of_violence = case_when(
           type_of_violence == 1 ~ 19,
           type_of_violence == 2 ~ 19,
           type_of_violence == 3 ~ 18)) %>%
  summarize(ucdp_total = n()) %>%
  rename(event_type = type_of_violence)

conflict_data <- conflict_data %>%
  merge(organized, by = c("country_code", "year", "event_type"), all = TRUE)
```


## WORLD BANK PEACE DATA


```{r peace_data}
# WORLD BANK PEACE DATA

# Need to add all iso codes, some missing; don't merge yet

peace_months <- read_excel("ViEWS/peace_months.xls")

peace_months_fixed <- peace_months %>%
  select(country, year, peaceyears) %>%
  rename(country_name = country) %>%
  merge(country_code, by = "country_name", all.x = TRUE) %>%
  select(-c(country_name)) %>%
  mutate(year = as.character(year)) %>%
  drop_na(year, country_code)

peace_months_fixed = peace_months_fixed[-1,]
peace_months_fixed$peaceyears[is.na(peace_months_fixed$peaceyears)] <- 0
```


```{r write}
# WRITE TO CSV

# write_csv(full_data, path = "ViEWS/full_data.csv")
# drop_delete(path = "political_data")
# drop_upload(file = "ViEWS/full_data.csv", path = "political_data")
```

```